### ISSUE TITLE
Remove duplication of No-Progress values from *Dead.csv files

### ISSUE THREAD

**Issue by laylar** [smartercleanup/spreadsheet-muncher#4]
*Dead.csv currently still includes no-progress values, as it had before I added the *NoProg.csv result. To fix this, we'd need to remove part of line 134 and all of 135: 
-134: or\
-135: row['Progress'] == 'No Progress'
I separated the two so that we could choose to color them both red, or color *Dead.csv black, as Jake said we may do.

**Comment by modulitos** [comment]
Thanks for the update! I'll push a fix for this soon...
