### ISSUE TITLE
find the 2 missing Georgetown records...

### ISSUE THREAD

**Issue by futuresoup** [smartercleanup/spreadsheet-muncher#7]
There are 106 records on the original spreadsheet

But only 104 records imported into Mapbox...

---

There are 18 csvs that have to be re-stiched and analyzed to figure out what two records are missing and why...

We could also wait until we implement our new publishing workflow, where we will spit out the 106 records as individual html files, and see what's up at that time.

**Comment by laylar** [comment]
Mystery unraveled! It turns out, we missed the two locations in the "Seattle Design District" category.
